# Path where the Gentoo package database is located
pkg_dir: /var/db/pkg

# Calculate MD5 sums on file system and compare with records
# in the package database. This causes the file system scan to
# be very slow.
md5:   false

# Compare filesystem mtimes with mtimes recorded in the package database.
mtime: false

# Do not recurse into the following directories when scanning the file system.
ignore_paths:
        - /boot
        - /dev
        - /etc/ssl/certs
        - /home
        - /media
        - /mnt
        - /proc
        - /root
        - /run
        - /sys
        - /tmp
        - /usr/local
        - /usr/src
        - /var/cache/distfiles
        - /var/db/pkg
        - /var/db/repos/gentoo
        - /var/tmp

# Specifically ignore the following files when scanning the file system.
ignore_files:
        - /
#        - /var/log/ignore_me.log
